export const MANAGER_LOADING ='MANAGER_LOADING';
export const ADD_MANAGER ='ADD_MANAGER';
export const MANAGER_FAILED ='MANAGER_FAILED';
export const SEND_MANAGER ='SEND_MANAGER';
export const SEND_MANAGER_FAILED ='SEND_MANAGER_FAILED';

export const RESTAURANT_LOADING ='RESTAURANT_LOADING';
export const ADD_RESTAURANT ='ADD_RESTAURANT';
export const POST_RESTAURANT ='POST_RESTAURANT';
export const POST_RESTAURANT_FAIL ='POST_RESTAURANT_FAIL';
export const RESTAURANT_FAILED ='RESTAURANT_FAILED';
export const RESTAURANT_ADDRESS ='RESTAURANT_ADDRESS';
export const RESTAURANT_UPLOAD ='RESTAURANT_UPLOAD';
export const RESTAURANT_UPLOAD_FAIL ='RESTAURANT_UPLOAD_FAIL';
export const RESTAURANT_DELETE='RESTAURANT_DELETE';
export const RESTAURANT_DELETE_FAIL='RESTAURANT_DELETE_FAIL'
export const RESTAURANT_UPDATE='RESTAURANT_UPDATE'
export const RESTAURANT_UPDATE_FAIL='RESTAURANT_UPDATE_FAIL'
export const LOAD_ALL_RESTAURANTS = 'LOAD_ALL_RESTAURANTS';
export const LOAD_RESTAURANTS_FAIL ='LOAD_RESTAURANTS_FAIL';

export const  LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const  LOGIN_FAILURE= 'LOGIN_FAILURE';
export const  LOGOUT= 'LOGOUT';

export const SEND_USER ='SEND_USER';
export const SEND_USER_FAILED ='SEND_USER_FAILED';
export const ADD_USER= 'ADD_USER';
export const USER_LOADING= 'USER_LOADING';
export const USER_FAILED= 'USER_FAILED';

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const USER_DISPLAY_FAIL ='USER_DISPLAY_FAIL';
export const GET_CURR_USER_ADDRESS = 'GET_CURR_USER_ADDRESS';

export const ADD_DISH ='ADD_DISH';
export const DISH_LOADING ='DISH_LOADING';
export const DISH_FAILED ='DISH_FAILED';
export const SEND_DISH ='SEND_DISH';
export const ADD_DISH_FAILED ='ADD_DISH_FAILED';
export const DISH_UPLOAD ='DISH_UPLOAD';
export const DISH_UPLOAD_FAIL ='DISH_UPLOAD_FAIL';
export const DISH_DELETE ='DISH_DELETE';
export const DISH_DELETE_FAIL ='DISH_DELETE_FAIL';
export const DISH_UPDATE_FAIL ='DISH_UPDATE_FAIL';
export const DISH_UPDATE ='DISH_UPDATE';

export const ADD_REVIEW= 'ADD_REVIEW';
export const REVIEW_LOADING= 'REVIEW_LOADING';
export const REVIEW_FAILED= 'REVIEW_FAILED';
export const SEND_REVIEW = 'SEND_REVIEW';
export const REVIEW_CHECK = 'REVIEW_CHECK';
export const FETCH_REVIEW = 'FETCH_REVIEWS';
export const FETCH_REVIEW_FAILED = 'FETCH_REVIEW_FAILED';

export const FETCH_DISHES = 'FETCH_DISHES';
export const FETCH_DISH_FAILED = 'FETCH_DISH_FAILED';
export const DP_UPLOAD_FAIL= 'DP_UPLOAD_FAIL';
export const DP_UPLOAD= 'DP_UPLOAD';
export const SET_LOCATION_FAILED= 'SET_LOCATION_FAILED';
export const SET_LOCATION ='SET_LOCATION'
