export const MANAGER_LOADING ='MANAGER_LOADING';
export const ADD_MANAGER ='ADD_MANAGER';
export const MANAGER_FAILED ='MANAGER_FAILED';
export const SEND_MANAGER ='SEND_MANAGER';
export const SEND_MANAGER_FAILED ='SEND_MANAGER_FAILED';

export const RESTAURANT_LOADING ='RESTAURANT_LOADING';
export const ADD_RESTAURANT ='ADD_RESTAURANT';
export const POST_RESTAURANT ='POST_RESTAURANT';
export const POST_RESTAURANT_FAIL ='POST_RESTAURANT_FAIL';
export const RESTAURANT_FAILED ='RESTAURANT_FAILED';
export const RESTAURANT_ADDRESS ='RESTAURANT_ADDRESS';
export const RESTAURANT_UPLOAD ='RESTAURANT_UPLOAD';
export const RESTAURANT_UPLOAD_FAIL ='RESTAURANT_UPLOAD_FAIL';

export const  LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const  LOGIN_FAILURE= 'LOGIN_FAILURE';
export const  LOGOUT= 'LOGOUT';

export const SEND_USER ='SEND_USER';
export const SEND_USER_FAILED ='SEND_USER_FAILED';
export const ADD_USER= 'ADD_USER';
export const USER_LOADING= 'USER_LOADING';
export const USER_FAILED= 'USER_FAILED';